# Generated by Django 2.0.7 on 2018-08-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=20)),
                ('img_path', models.CharField(max_length=2000)),
            ],
        ),
    ]
