# Generated by Django 2.0.7 on 2018-08-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180819_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='locality',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
